server:
  port: 8080
  context-path: /rent
  compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain

application:
  url: http://localhost
  session:
    redis:
      host: 62.80.167.165
      port: 6379
    cookie:
      name: UISESSION
      path: /

storage:
  host:
    scheme: http
    address: localhost
    port: 8086
    context-path: /storage

mongo:
    db:
      uri: mongodb://gup:1qazxcft6@mongo-1.dev.gup.ua,mongo-2.dev.gup.ua,mongo-3.dev.gup.ua/heroku_lktlmxlq?replicaSet=GUP0
spring:
  session:
    store-type: redis
  profiles:
    active: pre-prod
  thymeleaf:
    cache: false

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: 7b5a38705d7b3562655925406a652e32
      clientSecret: 655f523128212d6e70634446224c2a48
      accessTokenUri: https://oauth.dev.gup.ua/oauth/oauth/token
      checkTokenUri: https://oauth.dev.gup.ua/oauth/api/oauth/check_token
      userAuthorizationUri: https://oauth.dev.gup.ua/oauth/oauth/authorize
    resource:
      userInfoUri: https://oauth.dev.gup.ua/oauth/api/user/principal
    sso: /api/user/login

#Mail Server Configuration for production
email:
  services:
    smtp:
      host: corp.gup.ua
      port: 25
      username: website@corp.gup.ua
      password: aJpDgDxPGX40Yf3H
      auth: true
      starttls:
        enable: true

