package ua.com.itproekt.gup.model.activityfeed;


public enum EventType {
    OFFER_RESERVATION,
    OFFER_RENT,
    MONEY_TRANSFER_TO_USER,
    NEW_ORDER,
    ORDER_CANCEL_BY_BUYER,
    ORDER_REJECTED_BY_SELLER,
    ORDER_ACCEPTED,
    ORDER_SENT,
    ORDER_COMPLETED,
    ORDER_BUYER_COMMENT,
    ORDER_SELLER_COMMENT,
}
