//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.18 at 03:20:00 AM EEST 
//


package com.bank.ws.wsdl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inviteCode" type="{ws.bank.com/wsdl}inviteCode"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inviteCode"
})
@XmlRootElement(name = "getInviteCodeResponse")
public class GetInviteCodeResponse {

    @XmlElement(required = true)
    protected InviteCode inviteCode;

    /**
     * Gets the value of the inviteCode property.
     * 
     * @return
     *     possible object is
     *     {@link InviteCode }
     *     
     */
    public InviteCode getInviteCode() {
        return inviteCode;
    }

    /**
     * Sets the value of the inviteCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InviteCode }
     *     
     */
    public void setInviteCode(InviteCode value) {
        this.inviteCode = value;
    }

}
