package ua.com.gup.common.model.mongo.operation;

public enum OperationType {

    RENT_OFFER_CREATE,
    RENT_OFFER_UPDATE,

    PROFILE_BONUS_CREATED,
    PROFILE_BONUS_UPDATE,
    PROFILE_BONUS_ACTIVATE_OR_DEACTIVATE,
    PROFILE_BONUS_EXECUTE_SCENARIO,

    USER_BAN,
    USER_UNBAN,
    UPDATE_USER_BY_ADMIN,

    UAPAY_DIRECT_P2P_PAYMENT_CREATE,
    UAPAY_DIRECT_P2P_PAYMENT_CONFIRM,
    UAPAY_DIRECT_P2P_PAYMENT_SHOW,
    UAPAY_ECOM_PAYMENT_COMPLETE,

    UAPAY_CANCEL_ORDER,
    UAPAY_VIEW_ORDER,
    UAPAY_CREATE_SESSION


}
