//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.17 at 09:49:36 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://service.bank.com/wsdl", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bank.service.wsdl;
