package ua.com.gup.model.activityfeed;

/**
 * This class describe all types of events type for notifications.
 *
 * @author Kobylyatskyy Alexander
 */
public enum EventType {
    OFFER_RESERVATION,
    OFFER_RENT,

    OFFER_FAIL,

    OFFER_COMPLETE,

    OFFER_MODERATOR_CHANGE_CATEGORY,

    MONEY_TRANSFER_TO_USER,

    NEW_ORDER,
    ORDER_CANCEL_BY_BUYER,
    ORDER_REJECTED_BY_SELLER,
    ORDER_ACCEPTED,
    ORDER_SENT,
    ORDER_COMPLETED,

    ORDER_BUYER_COMMENT,
    ORDER_SELLER_COMMENT,
    ORDER_BUYER_COMMENT_EDIT,

    ORDER_BUYER_DELETE_FEEDBACK,
    ORDER_SELLER_DELETE_FEEDBACK,

    ORDER_BUYER_FEEDBACK_LIKE,
    ORDER_BUYER_FEEDBACK_DISLIKE,
    ORDER_BUYER_FEEDBACK_SPAM,

    ORDER_SELLER_FEEDBACK_LIKE,
    ORDER_SELLER_FEEDBACK_DISLIKE,
    ORDER_SELLER_FEEDBACK_SPAM
}
